version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "my_project.wsgi:application"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:15
    restart: always
    container_name: postgres_master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: impactadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  postgres_data:
