version: '3.8'

services:
  postgres_master:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres_master
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres_master

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true  # Ajuda com hot reload dentro do Docker
    command: "npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  postgres_data:
