services:
  - type: web
    name: impacta-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: dockerfile
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHONUNBUFFERED
        value: 1
